url_docker_registry_dockerhub = "https://hub.docker.com/r/hashicorp/vault-plugin-auth-azure"
url_docker_registry_ecr       = "https://gallery.ecr.aws/hashicorp/vault-plugin-auth-azure"
url_source_repository         = "https://github/hashicorp/vault-plugin-auth-azure"
url_project_website           = "https://www.vaultproject.io/"
url_license                   = "https://github.com/hashicorp/vault-plugin-auth-azure/blob/main/LICENSE"
url_release_notes             = "https://www.vaultproject.io/docs/release-notes"